[package]
name = "hackathon-rust"
version = "0.1.0"
authors = ["Ian Graham Martinez <Ian.graham28@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4.0.0"